version:  '3'
services:
#serviços que localiza dockerfile e executa
  node1:
    build:
      dockerfile: ./docker/angular_aps.dockerfile
      context:  .
    image: aps_front/node1
    ports:
      - "80:80"
    networks:
      - cnp_1

  sonarqube:
    image: sonarqube:latest
    #restart: unless-stopped
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - cnp_1
  
  db:
    image: postgres:latest
    #restart: unless-stopped
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube_db:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data    
    networks:
      - cnp_1
#redes internas bridge do Docker
networks:
  cnp_1:
    driver: bridge

volumes:
  postgresql_data:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_db:
  sonarqube_extensions:

