version:  '3'
services:
#serviços que localiza dockerfile e executa
  node1:
    build:
      dockerfile: ./docker/angular_aps.dockerfile
      context:  .
    image: aps_front/node1
    ports:
      - "80:80"
    networks:
      - cnp_1
    
#redes internas bridge do Docker
networks:
  cnp_1:
    driver: bridge

